[package]
name = "hydock"
version = "0.1.0"
edition = "2024"

[dependencies]
glib = "0.21.0"
gtk4 = "0.9.0"
gtk4-layer-shell = "0.5.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
