[package]
name = "hydock"
version = "1.1.0-dev"
edition = "2024"

[dependencies]
glib = "0.21.0"
gtk4 = "0.9.0"
gtk4-layer-shell = "0.5.0"
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1.0.0"
toml = "0.9.4"
