[config]

# Shell command to execute when the app launcher is clicked
app_launcher_command = "rofi -show drun"

# Which icon to use for app launcher
app_launcher_icon = "applications-all-symbolic"

# Hide dock when unfocused
auto_hide = false

# Enable random order of app icons
# You don't actually want this, idk why did I add this
chaos_mode = false

# Anchor of the dock panel
dock_position = "bottom"

# List of application class names that should never appear in the dock
ignore_applications = []

# Which icons to use for specified class names
override_app_icons = {}

# List of application class names that should always appear in the dock
pinned_applications = []

# Add app launcher button on the right
show_app_launcher = true

# Add separator between apps and app launcher
show_separator = true
